### ISSUE TITLE
init failed

### ISSUE THREAD

**Issue by antoine4ucsd** [cdelahaye/SeqFaiLR#1]
Hello
First, thank you for this impressive work and nice paper. very inspiring and insightful!
I am also trying to investigate my NPC data and evaluate potential error rate and PCR biases. 
I would like to evaluate your workflow on my data but I cannot set up SeqFaiLR properly... 
I am using a Mac with Python 3.10.4 installed (can move to linux if needed but I'd rather not)
sorry but I cannot even start the init cmd. In the main folder:

```
./seqfailr -i
grep: invalid option -- P

```

all suggestions would help! thank you
(seqborn, minimap already  installed)

**Comment by antoine4ucsd** [comment]
more info. I just tried on a linux env, after installing seaborn (conda) but still not working?

```
 ./seqfailr --init

===== Running ./Scripts/initialize.sh =====
Check wether minimap2 is installed
  Installing minimap2 aligner:
./Scripts/initialize.sh: line 27: git: command not found
mv: cannot stat 'minimap2': No such file or directory
./Scripts/initialize.sh: line 29: cd: ./Scripts/minimap2: No such file or directory
    minimap2 installed.
Done.

Look at the organization of the species' folders
Package seaborn is required, please install it
Failed.

```
strange since seaborn IS installed.
thank you

**Comment by cdelahaye** [comment]
Hello,
First, thanks for you feedback, that helps me to improve and debug this code!

_For the ./seqfailr -i error_
I've never used Mac before, I did not realize commands such as grep do not always have same options. Sorry for that.
I've corrected it, I think it should work now. Please tell me if you encounter any other errors of this kind.

_For the minimap error_
That's my fault here again. I assumed (wrongly) users would not have installed minimap2 and that they would have thus install it with the init script. I've corrected it, so now it should detect if minimap2 is already installed.

_For the seaborn error_
Strange, indeed. I have no idea what it could be due to... 
Can you check seaborn was correctly installed and loaded when you run the seqfailr command?
For example, you can try to run this small python script and see if it leads to an error:
  ```
  import seaborn as sns; sns.set_theme()
  ```
  
  Clara

**Comment by antoine4ucsd** [comment]
Great. working on it now - I will get back to you asap. fingers crossed.
thank you

**Comment by antoine4ucsd** [comment]
much better but still problem with minimap2 pre-installed.
no error with init but when running seqfailR -all, the log is looking for Script/minimap2/minimap2 but it does not exist in this path. 
I did something inelegant: 
- I uninstalled minimap2 from conda env. 
- then I ran seqfailR --init which installed minimap2 and creates the required folder 
- BUT I had to reinstall minimap2 via conda afterwards.
- then I ran seqfailR --init with no error
- then I am trying to run eqfailR --all

> it is not working as expected for several scripts...

see log attached
we are making progress!!! 

btw: if you are interested, would be happy to discuss further via mp.

thank you

[log2.txt](https://github.com/cdelahaye/SeqFaiLR/files/8645416/log2.txt)

**Comment by antoine4ucsd** [comment]
I may have found a bug: your code is  looking for Script/minimap2/minimap2 but the file is named minimap2.1 so I renamed it.  I also had to install mappy manually and clear the alignment folder. 
now it is running but seems very very slow... maybe stuck but I have no way to confirm. already 25' (latest macbook pro M1)

```
./seqfailr --all

===== Running ./Scripts/initialize.sh =====
Check wether minimap2 is installed
Done.

Look at the organization of the species' folders
 Species will not be grouped.
Done.

Compute GC content of reference genome for each species, and assign it a color for future graphs
  File ./Data/species_color_GC.txt already exists, do not compute it again (or remove it first).
Done.

Checks association species-genome and that files are correctly named
Done.

Computes reverse complements of each reference genome file
  Acinetobacter_pittii.fasta
Done.

=====
Running ./Scripts/map.sh

Mapping reads
  Acinetobacter_pittii: forward...
```

thank you

**Comment by antoine4ucsd** [comment]
Great news! I made it works
the problem had to do with minimap2 since the scripts was still looking for ./Scripts/minimap2/minimap2 which does not work so I manually edited map.sh on lines 50 and 70 so now it is ALWAYS calling the conda version of minimap2 👍 

```
    minimap2 --MD --eqx -ax map-ont
```
instead of 
```
    ./Scripts/minimap2/minimap2 --MD --eqx -ax map-ont

```

now I am eager to try on my own data...
I will likely have questions. can we continue the dicussion via mp?

**Comment by cdelahaye** [comment]
Damn, so sorry, I forgot to correct that in the other scripts... I will make a new commit soon. Sorry for that.
Yes of course, I'll send you an email once I've done the commit (today if I have time, or tomorrow)

**Comment by antoine4ucsd** [comment]
no worries. exploring my data now...
looking forward to discussing with you

**Comment by cdelahaye** [comment]
Hi,
We can discuss by mail if you want, here is my address (I could not find yours): clara.delahaye@irisa.fr
